GET http://localhost:3030/Author/?page=1&pagSize=5
####

POST http://localhost:3030/Author
Content-Type: application/json

{
    "firstName": "Yoshi",
    "surName": "d",
    "email":"yoshi.bauda@gmail.com",
    "birthDay": "12-01-1994",
    "avatar": "https://biografieonline.it/img/bio/p/Pippo_Baudo.jpg"
}

####
DELETE http://localhost:3030/Author/65f36c1a42e5001df345efed

####

PATCH http://localhost:3030/Author/65f36c1a42e5001df345efed
Content-Type: application/json

{
    "surName": "BAUDO"
}

####
GET http://localhost:3030/Author/byName/pap

####
GET http://localhost:3030/blogPosts

####

POST http://localhost:3030/blogPosts
Content-Type: application/json

{
    "category": "Feedback",
    "title": "Buono",
    "cover": "",
    "readTime":{
        "value":1,
        "unit": "times"
    },
    "author":{
        "name":"Me",
        "avatar":""
    },
    "content":"Tutto abbastanza bello"
}

####
DELETE http://localhost:3030/blogPosts/65f77eccfd14db9c524e7928

####
PATCH http://localhost:3030/blogPosts/65f7729a4a81f357735bdd4c
Content-Type: application/json

{   
    "cover":"nuovaCover"
}


####
GET http://localhost:3030/users
authorization: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImFuZHJlYSIsImVtYWlsIjoiYW5kcmVhLnJhbmVyaTk1QGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxMTcxMDQxNywiZXhwIjoxNzExNzExMzE3fQ.LEiXh8COIqainx2q-Vg1Um4JaSLZn5ZqmZL8_p4YpLU'

####
POST http://localhost:3030/users
Content-Type: application/json

{
    "userName": "andrea",
    "password":"ciao12",
    "email":"andrea.raneri94@gmail.com",
    "age":29,
    "role":"admin"
}
####
DELETE http://localhost:3030/users/660496d24ca8da9fa8156558
####
POST http://localhost:3030/login
Content-Type: application/json

{
    "email":"andrea.raneri95@gmail.com",
    "password":"ciao12"
}
