GET http://localhost:3030/Author/65f3237c49ae7041fd63ba67
####

POST http://localhost:3030/Author
Content-Type: application/json

{
    "firstName": "Pippo",
    "surName": "Baudo 4",
    "email":"pippo.baudo@gmail.com",
    "birthDay": "2000-01-01",
    "avatar": "https://biografieonline.it/img/bio/p/Pippo_Baudo.jpg"
}

####

PATCH 
